### ISSUE TITLE
Tier 3: Can we get access to back camera?

### ISSUE THREAD

**Issue by yannbouteiller** [microsoft/AirSim-NeurIPS2019-Drone-Racing#74]
Hello,

The first version of the competition rules stated that tier 3 would give access to both front and back camera images, but apparently the statement about back camera has been removed in the competition guidelines. Is this on purpose to avoid competitive AI in tier 3 and transform it into a variant of tier 2 ?

Even though I am not sure to succeed at creating such difficult controllers myself, I do think that access to back camera is what makes tier 3 interesting for NeurIPS, because it enables the possibility to block the chasing drone. Without it, we probably won't see any adversarial AI in tier 3, because it is an excessively difficult behavior to spin in order to see both the track and the chasing drone, and if the leading drone cannot see the chasing drone then the leading drone becomes a non-adversarial moving obstacle.

Regards,
Yann

**Comment by madratman** [comment]
I think I mentioned this on another issue thread that we decided to back out of that as our frame rate was getting killed with two cameras, sadly. 
I think we can still get the position of the other drone with simgetmultirotorpose / simgetvehiclepose, and thereby do adversarial stuff. getting the pose of the other drone directly, instead of estimating it from cameras makes the tier 3 tractable as well. 
But I agree with essence of your comments - we'll consider this for this next iteration of this competition.
